# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Frayt Driver CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Create .env file
        uses: SpicyPizza/create-envfile@v1.2
        with:
          envkey_GOOGLE_API_KEY: ${secrets.GOOGLE_API_KEY}
          envkey_PRD_STRIPE_PUBLISH_KEY: ${{ secrets.PRD_STRIPE_PUBLISH_KEY }}
          envkey_PRD_BASE_URL: 'https://api.frayt.com/api/internal/v2.1/'
      - uses: actions/cache@v1
        id: node-modules-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ hashFiles(format('{0}{1}', github.workspace, 'package-lock.json')) }}
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: install dependencies
        run: npm install
        # TODO: hope this starts working on github CI
      # - name: check formatting
      # run: npm run check-format
      - name: Run tests
        run: npm test
  deploy-ios:
    needs: build
    name: Deploy iOS Staging
    if: github.ref == 'refs/heads/master' && !startsWith( github.ref, 'refs/tags/codepush/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Create .env file
        uses: SpicyPizza/create-envfile@v1.2
        with:
          envkey_GOOGLE_API_KEY: ${secrets.GOOGLE_API_KEY}
          envkey_PRD_STRIPE_PUBLISH_KEY: ${{ secrets.PRD_STRIPE_PUBLISH_KEY }}
          envkey_PRD_BASE_URL: 'https://api.frayt.com/api/internal/v2.1/'
      - name: Install Dependencies
        run: npm install
      - name: Deploy to Codepush
        uses: NishanthShankar/codepush-action@master
        with:
          args: release-react -a elijah-frayt.com/Frayt-Driver-IOS -d Staging
        env:
          APPCENTER_ACCESS_TOKEN: ${{ secrets.APPCENTER_ACCESS_TOKEN_IOS }}
  deploy-android:
    needs: build
    name: Deploy Android Staging
    if: github.ref == 'refs/heads/master' && !startsWith( github.ref, 'refs/tags/codepush/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Create .env file
        uses: SpicyPizza/create-envfile@v1.2
        with:
          envkey_GOOGLE_API_KEY: ${secrets.GOOGLE_API_KEY}
          envkey_PRD_STRIPE_PUBLISH_KEY: ${{ secrets.PRD_STRIPE_PUBLISH_KEY }}
          envkey_PRD_BASE_URL: 'https://api.frayt.com/api/internal/v2.1/'
      - name: Install Dependencies
        run: npm install
      - name: Deploy to Codepush
        uses: NishanthShankar/codepush-action@master
        with:
          args: release-react -a elijah-frayt.com/Frayt-Driver-Android -d Staging
        env:
          APPCENTER_ACCESS_TOKEN: ${{ secrets.APPCENTER_ACCESS_TOKEN_ANDROID }}
